/*******************************************************************************
 * Copyright (c) 2016 Politecnico di Torino.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Politecnico di Torino - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 04:24:18 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://protectionInstantiation.akb.adss.aspire_fp7.eu", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.aspire_fp7.adss.akb.protectioninstantiation;
