/*******************************************************************************
 * Copyright (c) 2016 Politecnico di Torino.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Politecnico di Torino - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 04:24:18 PM CEST 
//


package eu.aspire_fp7.adss.akb.protectioninstantiation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="protectionInstantiation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="protectionInstantiationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="protectionName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="dataObfuscation"/>
 *                         &lt;enumeration value="multiThreadedCryptography"/>
 *                         &lt;enumeration value="softwareTimeBomb"/>
 *                         &lt;enumeration value="whiteBoxCryptography"/>
 *                         &lt;enumeration value="softVM"/>
 *                         &lt;enumeration value="antiDebugging"/>
 *                         &lt;enumeration value="callStackChecks"/>
 *                         &lt;enumeration value="codeGuards"/>
 *                         &lt;enumeration value="binaryCodeControlFlowObfuscation"/>
 *                         &lt;enumeration value="clientServerSplitting"/>
 *                         &lt;enumeration value="codeMobility"/>
 *                         &lt;enumeration value="staticRemoteAttestation"/>
 *                         &lt;enumeration value="controlFlowGraphTagging"/>
 *                         &lt;enumeration value="antiCloning"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="variableAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="codeRegionAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="attestatorAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="verifierAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="toolForDeployment" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   &lt;element name="clientTimeOverhead" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="clientMemoryOverhead" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serverTimeOverhead" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="serverMemoryOverhead" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="networkOverhead" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protectionInstantiation"
})
@XmlRootElement(name = "protectionInstantiationsList")
public class ProtectionInstantiationsList {

    protected List<ProtectionInstantiationsList.ProtectionInstantiation> protectionInstantiation;

    /**
     * Gets the value of the protectionInstantiation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the protectionInstantiation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtectionInstantiation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProtectionInstantiationsList.ProtectionInstantiation }
     * 
     * 
     */
    public List<ProtectionInstantiationsList.ProtectionInstantiation> getProtectionInstantiation() {
        if (protectionInstantiation == null) {
            protectionInstantiation = new ArrayList<ProtectionInstantiationsList.ProtectionInstantiation>();
        }
        return this.protectionInstantiation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="protectionInstantiationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="protectionName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="dataObfuscation"/>
     *               &lt;enumeration value="multiThreadedCryptography"/>
     *               &lt;enumeration value="softwareTimeBomb"/>
     *               &lt;enumeration value="whiteBoxCryptography"/>
     *               &lt;enumeration value="softVM"/>
     *               &lt;enumeration value="antiDebugging"/>
     *               &lt;enumeration value="callStackChecks"/>
     *               &lt;enumeration value="codeGuards"/>
     *               &lt;enumeration value="binaryCodeControlFlowObfuscation"/>
     *               &lt;enumeration value="clientServerSplitting"/>
     *               &lt;enumeration value="codeMobility"/>
     *               &lt;enumeration value="staticRemoteAttestation"/>
     *               &lt;enumeration value="controlFlowGraphTagging"/>
     *               &lt;enumeration value="antiCloning"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="variableAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="codeRegionAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="attestatorAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="verifierAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="toolForDeployment" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *         &lt;element name="clientTimeOverhead" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="clientMemoryOverhead" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serverTimeOverhead" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="serverMemoryOverhead" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="networkOverhead" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "protectionInstantiationName",
        "protectionName",
        "variableAnnotation",
        "codeRegionAnnotation",
        "attestatorAnnotation",
        "verifierAnnotation",
        "toolForDeployment",
        "clientTimeOverhead",
        "clientMemoryOverhead",
        "serverTimeOverhead",
        "serverMemoryOverhead",
        "networkOverhead"
    })
    public static class ProtectionInstantiation {

        @XmlElement(required = true)
        protected String protectionInstantiationName;
        @XmlElement(required = true)
        protected String protectionName;
        protected String variableAnnotation;
        protected String codeRegionAnnotation;
        protected String attestatorAnnotation;
        protected String verifierAnnotation;
        @XmlElement(required = true)
        protected List<String> toolForDeployment;
        @XmlElement(required = true)
        protected String clientTimeOverhead;
        @XmlElement(required = true)
        protected String clientMemoryOverhead;
        protected String serverTimeOverhead;
        protected String serverMemoryOverhead;
        @XmlElement(required = true)
        protected String networkOverhead;

        /**
         * Gets the value of the protectionInstantiationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtectionInstantiationName() {
            return protectionInstantiationName;
        }

        /**
         * Sets the value of the protectionInstantiationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtectionInstantiationName(String value) {
            this.protectionInstantiationName = value;
        }

        /**
         * Gets the value of the protectionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtectionName() {
            return protectionName;
        }

        /**
         * Sets the value of the protectionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtectionName(String value) {
            this.protectionName = value;
        }

        /**
         * Gets the value of the variableAnnotation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariableAnnotation() {
            return variableAnnotation;
        }

        /**
         * Sets the value of the variableAnnotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariableAnnotation(String value) {
            this.variableAnnotation = value;
        }

        /**
         * Gets the value of the codeRegionAnnotation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeRegionAnnotation() {
            return codeRegionAnnotation;
        }

        /**
         * Sets the value of the codeRegionAnnotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeRegionAnnotation(String value) {
            this.codeRegionAnnotation = value;
        }

        /**
         * Gets the value of the attestatorAnnotation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttestatorAnnotation() {
            return attestatorAnnotation;
        }

        /**
         * Sets the value of the attestatorAnnotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttestatorAnnotation(String value) {
            this.attestatorAnnotation = value;
        }

        /**
         * Gets the value of the verifierAnnotation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerifierAnnotation() {
            return verifierAnnotation;
        }

        /**
         * Sets the value of the verifierAnnotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerifierAnnotation(String value) {
            this.verifierAnnotation = value;
        }

        /**
         * Gets the value of the toolForDeployment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the toolForDeployment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getToolForDeployment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getToolForDeployment() {
            if (toolForDeployment == null) {
                toolForDeployment = new ArrayList<String>();
            }
            return this.toolForDeployment;
        }

        /**
         * Gets the value of the clientTimeOverhead property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientTimeOverhead() {
            return clientTimeOverhead;
        }

        /**
         * Sets the value of the clientTimeOverhead property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientTimeOverhead(String value) {
            this.clientTimeOverhead = value;
        }

        /**
         * Gets the value of the clientMemoryOverhead property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientMemoryOverhead() {
            return clientMemoryOverhead;
        }

        /**
         * Sets the value of the clientMemoryOverhead property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientMemoryOverhead(String value) {
            this.clientMemoryOverhead = value;
        }

        /**
         * Gets the value of the serverTimeOverhead property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerTimeOverhead() {
            return serverTimeOverhead;
        }

        /**
         * Sets the value of the serverTimeOverhead property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerTimeOverhead(String value) {
            this.serverTimeOverhead = value;
        }

        /**
         * Gets the value of the serverMemoryOverhead property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerMemoryOverhead() {
            return serverMemoryOverhead;
        }

        /**
         * Sets the value of the serverMemoryOverhead property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerMemoryOverhead(String value) {
            this.serverMemoryOverhead = value;
        }

        /**
         * Gets the value of the networkOverhead property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkOverhead() {
            return networkOverhead;
        }

        /**
         * Sets the value of the networkOverhead property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkOverhead(String value) {
            this.networkOverhead = value;
        }

    }

}
