/*
 * generated by Xtext 2.10.0
 */
package eu.aspire_fp7.adss.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class RulesLanguageScopeProvider extends AbstractRulesLanguageScopeProvider {

}
