/*
 * generated by Xtext 2.10.0
 */
package eu.aspire_fp7.adss.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.IXtextEditorCallback.NullImpl

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class RulesLanguageUiModule extends AbstractRulesLanguageUiModule
{
	override bindIXtextEditorCallback()
	{
		return NullImpl
	}
}
