/*
 * generated by Xtext 2.10.0
 */
package eu.aspire_fp7.adss


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RulesLanguageRuntimeModule extends AbstractRulesLanguageRuntimeModule {
}
