/*
 * generated by Xtext 2.10.0
 */
package eu.aspire_fp7.adss.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RulesLanguageValidator extends AbstractRulesLanguageValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					RulesLanguagePackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
