/*******************************************************************************
 * Copyright (c) 2016 Politecnico di Torino.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Politecnico di Torino - initial API and implementation
 *******************************************************************************/
/**
 * generated by Xtext 2.10.0
 */
package eu.aspire_fp7.adss.rulesLanguage;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Action</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see eu.aspire_fp7.adss.rulesLanguage.RulesLanguagePackage#getAction()
 * @model
 * @generated
 */
public enum Action implements Enumerator
{
  /**
   * The '<em><b>DECRYPT AES128 CBC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECRYPT_AES128_CBC_VALUE
   * @generated
   * @ordered
   */
  DECRYPT_AES128_CBC(0, "DECRYPT_AES128_CBC", "decrypt:AES128-CBC"),

  /**
   * The '<em><b>DECRYPT AES128 ECB</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECRYPT_AES128_ECB_VALUE
   * @generated
   * @ordered
   */
  DECRYPT_AES128_ECB(1, "DECRYPT_AES128_ECB", "decrypt:AES128-ECB"),

  /**
   * The '<em><b>ENCRYPT AES128 CBC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ENCRYPT_AES128_CBC_VALUE
   * @generated
   * @ordered
   */
  ENCRYPT_AES128_CBC(2, "ENCRYPT_AES128_CBC", "encrypt:AES128-CBC"),

  /**
   * The '<em><b>ENCRYPT AES128 ECB</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ENCRYPT_AES128_ECB_VALUE
   * @generated
   * @ordered
   */
  ENCRYPT_AES128_ECB(3, "ENCRYPT_AES128_ECB", "encrypt:AES128-ECB");

  /**
   * The '<em><b>DECRYPT AES128 CBC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DECRYPT AES128 CBC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DECRYPT_AES128_CBC
   * @model literal="decrypt:AES128-CBC"
   * @generated
   * @ordered
   */
  public static final int DECRYPT_AES128_CBC_VALUE = 0;

  /**
   * The '<em><b>DECRYPT AES128 ECB</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DECRYPT AES128 ECB</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DECRYPT_AES128_ECB
   * @model literal="decrypt:AES128-ECB"
   * @generated
   * @ordered
   */
  public static final int DECRYPT_AES128_ECB_VALUE = 1;

  /**
   * The '<em><b>ENCRYPT AES128 CBC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ENCRYPT AES128 CBC</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ENCRYPT_AES128_CBC
   * @model literal="encrypt:AES128-CBC"
   * @generated
   * @ordered
   */
  public static final int ENCRYPT_AES128_CBC_VALUE = 2;

  /**
   * The '<em><b>ENCRYPT AES128 ECB</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ENCRYPT AES128 ECB</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ENCRYPT_AES128_ECB
   * @model literal="encrypt:AES128-ECB"
   * @generated
   * @ordered
   */
  public static final int ENCRYPT_AES128_ECB_VALUE = 3;

  /**
   * An array of all the '<em><b>Action</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Action[] VALUES_ARRAY =
    new Action[]
    {
      DECRYPT_AES128_CBC,
      DECRYPT_AES128_ECB,
      ENCRYPT_AES128_CBC,
      ENCRYPT_AES128_ECB,
    };

  /**
   * A public read-only list of all the '<em><b>Action</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Action> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Action</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Action get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Action result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Action</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Action getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Action result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Action</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Action get(int value)
  {
    switch (value)
    {
      case DECRYPT_AES128_CBC_VALUE: return DECRYPT_AES128_CBC;
      case DECRYPT_AES128_ECB_VALUE: return DECRYPT_AES128_ECB;
      case ENCRYPT_AES128_CBC_VALUE: return ENCRYPT_AES128_CBC;
      case ENCRYPT_AES128_ECB_VALUE: return ENCRYPT_AES128_ECB;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Action(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Action
