/*******************************************************************************
 * Copyright (c) 2016 Politecnico di Torino.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Politecnico di Torino - initial API and implementation
 *******************************************************************************/
/**
 * generated by Xtext 2.10.0
 */
package eu.aspire_fp7.adss.rulesLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.aspire_fp7.adss.rulesLanguage.FunctionDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link eu.aspire_fp7.adss.rulesLanguage.FunctionDeclaration#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see eu.aspire_fp7.adss.rulesLanguage.RulesLanguagePackage#getFunctionDeclaration()
 * @model
 * @generated
 */
public interface FunctionDeclaration extends Condition
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see eu.aspire_fp7.adss.rulesLanguage.RulesLanguagePackage#getFunctionDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link eu.aspire_fp7.adss.rulesLanguage.FunctionDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
   * The list contents are of type {@link eu.aspire_fp7.adss.rulesLanguage.ParameterType}.
   * The literals are from the enumeration {@link eu.aspire_fp7.adss.rulesLanguage.ParameterType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute list.
   * @see eu.aspire_fp7.adss.rulesLanguage.ParameterType
   * @see eu.aspire_fp7.adss.rulesLanguage.RulesLanguagePackage#getFunctionDeclaration_Parameters()
   * @model unique="false"
   * @generated
   */
  EList<ParameterType> getParameters();

} // FunctionDeclaration
